//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelASPNETbyEddy
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblJeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJeu()
        {
            this.tblClassifications = new HashSet<tblClassification>();
            this.tblGenres = new HashSet<tblGenre>();
            this.tblPlateformes = new HashSet<tblPlateforme>();
            this.tblThemes = new HashSet<tblTheme>();
        }
    
        public int idJeu { get; set; }

        [Required(ErrorMessage = " Entrez un nom de Jeu ", AllowEmptyStrings = false)]
        /*[RegularExpression("([A-Z]|[a-z]|[0-9]){1,}", ErrorMessage = " Valeur invalide!!! ")]*/
        public string nomJeu { get; set; }

        [Required(ErrorMessage = " Entrez un nom de développeur ", AllowEmptyStrings = false)]
        /*[RegularExpression("([A-Z]|[a-z]|[0-9]){1,}", ErrorMessage = " Valeur invalide!!! ")]*/
        public string devellopeurJeu { get; set; }

        [Required(ErrorMessage = " Entrez une description de jeu ", AllowEmptyStrings = false)]
        /* [RegularExpression("([A-Z]|[a-z]|[0-9]){1,}", ErrorMessage = " Valeur invalide!!! ")]*/
        public string descriptionJeu { get; set; }

        [Required(ErrorMessage = " Entrez une configuration minimal ", AllowEmptyStrings = false)]
        /*[RegularExpression("([A-Z]|[a-z]|[0-9]){1,}", ErrorMessage = " Valeur invalide!!! ")]*/
        public string configurationMinimaleJeu { get; set; }
        public Nullable<int> idProjetTest { get; set; }
        public string tag { get; set; }
    
        public virtual tblProjetTest tblProjetTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClassification> tblClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGenre> tblGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlateforme> tblPlateformes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTheme> tblThemes { get; set; }
    }
}
